services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: askmemind-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: askmemind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: askmemind_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: