# POST /auth/register
# POST /chats?user_id=<USER_ID>
# GET /chats?user_id=<USER_ID>
# POST /chats/{chat_id}/messages?user_id=<USER_ID>
# GET /chats/{chat_id}/messages?user_id=<USER_ID>

@baseUrl = http://127.0.0.1:8000
@userId = replace-with-user-id
@chatId = replace-with-chat-id
@accessToken = replace-with-access-token
@documentsId= replace-with-document-id

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "abc@example.com",
  "password": "password123"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "abc@example.com",
  "password": "password1234"
}

###
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/chats
Authorization: Bearer {{accessToken}}

###
POST {{baseUrl}}/chats
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Local Smoke Chat"
}

###
GET {{baseUrl}}/chats/{{chatId}}/messages
Authorization: Bearer {{accessToken}}

###
POST {{baseUrl}}/chats/{{chatId}}/messages
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "create message"
}

###
POST {{baseUrl}}/documents/upload
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=UploadBoundary

--UploadBoundary
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf

< ./test.pdf
--UploadBoundary--

###
GET {{baseUrl}}/documents
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/documents/{{documentsId}}
Authorization: Bearer {{accessToken}}