"""add generic source fields

Revision ID: 0210dc0fe3b9
Revises: 345a77ca6187
Create Date: 2026-06-02 22:01:44.962831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0210dc0fe3b9'
down_revision: Union[str, Sequence[str], None] = '345a77ca6187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('start_time_seconds', sa.Float(), nullable=True))
    op.add_column('chunks', sa.Column('end_time_seconds', sa.Float(), nullable=True))
    op.alter_column('chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'start_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'end_char',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('documents', sa.Column('source_type', sa.String(length=50), server_default='pdf', nullable=False))
    op.alter_column('documents', 'source_type', server_default=None)
    op.alter_column(
        'documents',
        'pdf_metadata',
        new_column_name='source_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'documents',
        'source_metadata',
        new_column_name='pdf_metadata')
    op.drop_column('documents', 'source_type')
    op.alter_column('chunks', 'end_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'start_char',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chunks', 'end_time_seconds')
    op.drop_column('chunks', 'start_time_seconds')
    # ### end Alembic commands ###
