"""update chunk schema

Revision ID: 1cd421beba00
Revises: 0210dc0fe3b9
Create Date: 2026-06-04 20:10:46.699478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd421beba00'
down_revision: Union[str, Sequence[str], None] = '0210dc0fe3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding_provider', sa.String(length=50), nullable=True))
    op.add_column('chunks', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_chunks_document_id_chunk_index', 'chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunks_document_id_chunk_index', 'chunks', type_='unique')
    op.drop_column('chunks', 'embedding_dimensions')
    op.drop_column('chunks', 'embedding_provider')
    # ### end Alembic commands ###
